Update 15-matrices.yaml

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -1,32 +1,46 @@
 name: 15 - Working with Matrices
 on: workflow_dispatch
 jobs:
-  backwards-compatibility:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, windows-latest]
-        node-version: [20.x, 21.x, 22.x]
-        include:
-          - os: ubuntu-latest
-            node-version: 18.x
-          - os: ubuntu-latest
-            node-version: 21.x
-            tag: experimental
+  # backwards-compatibility:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-latest, windows-latest]
+  #       node-version: [20.x, 21.x, 22.x]
+  #       include:
+  #         - os: ubuntu-latest
+  #           node-version: 18.x
+  #         - os: ubuntu-latest
+  #           node-version: 21.x
+  #           tag: experimental
             
-    name: ${{ matrix.os }} - ${{ matrix.node-version }}
-    runs-on: ${{ matrix.os }}
+  #   name: ${{ matrix.os }} - ${{ matrix.node-version }}
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - name: Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #     - name: Fail if experimental
+  #       if: matrix.tag == 'experimental'
+  #       run: exit 1
+  #     - name: Perform some tests
+  #       run: |
+  #         echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
+  #         sleep 5
+  #     - name: Upload test result
+  #       run: echo "Uploading test results"
+  include-example:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        color: [red, green]
+        shape: [circle, square]
+        size: [small, large]
+        include:
+          - color: red
+            shape: triangle
+    name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
     steps:
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node-version }}
-      - name: Fail if experimental
-        if: matrix.tag == 'experimental'
-        run: exit 1
-      - name: Perform some tests
-        run: |
-          echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
-          sleep 5
-      - name: Upload test result
-        run: echo "Uploading test results"
+      - name: Dummy step
+        run: echo ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
